### ISSUE TITLE
issue installing requirements

### ISSUE THREAD

**Issue by xke** [AbubakrChan/crewai-business-product-launch#5]
Hi!
I'm not sure what version of Python is recommended, but I got errors when trying to run this demo on my local computer...

<img width="780" alt="Screenshot 2024-06-04 at 7 08 14 PM" src="https://github.com/AbubakrChan/crewai-UI-business-product-launch/assets/3505778/b7be39b5-a931-4663-a05e-cf914fc07067">

**Comment by AbubakrChan** [comment]
hey - sorry for the delay
I think you have a right python version to run crewai.
